// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.1.0";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -541507629;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__panel_api__config_snapshot_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "config_snapshot_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::ConfigSnapshot::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__custom_net_item_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "custom_net_item_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::CustomNetItem::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__detect_existing_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "detect_existing_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::detect_existing_service()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__get_panel_account_summary_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_panel_account_summary", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::get_panel_account_summary()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__get_service_overview_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_service_overview", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::get_service_overview()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__get_session_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_session", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, ()>((move || {
                     let output_ok = Result::<_,()>::Ok(crate::api::panel_api::get_session())?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__init_app_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_app", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::panel_api::init_app(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__install_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "install_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_target_dir = <String>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::install_service(api_target_dir)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__load_raw_config_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "load_raw_config", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::load_raw_config()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__load_structured_config_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "load_structured_config", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::load_structured_config()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__log_snapshot_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "log_snapshot_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::LogSnapshot::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__login_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "login", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_username = <String>::sse_decode(&mut deserializer);
let api_password = <String>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::login(api_username, api_password)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__logout_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "logout", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::logout()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__panel_account_summary_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "panel_account_summary_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::PanelAccountSummary::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__panel_session_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "panel_session_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::PanelSession::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__read_log_tail_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "read_log_tail", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_lines = <i32>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::read_log_tail(api_lines)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__restart_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "restart_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::restart_service()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__save_raw_config_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "save_raw_config", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
let api_restart = <bool>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::save_raw_config(api_raw, api_restart)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__save_structured_config_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "save_structured_config", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_payload = <crate::api::panel_api::StructuredConfig>::sse_decode(&mut deserializer);
let api_restart = <bool>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::save_structured_config(api_payload, api_restart)?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__service_detection_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "service_detection_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::ServiceDetection::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__service_overview_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "service_overview_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::ServiceOverview::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__service_process_info_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "service_process_info_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::ServiceProcessInfo::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__service_status_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "service_status_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::ServiceStatus::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__start_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "start_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::start_service()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__stop_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "stop_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::stop_service()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__structured_config_default_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "structured_config_default", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::panel_api::StructuredConfig::default())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__panel_api__uninstall_service_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "uninstall_service", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::uninstall_service()?;   Ok(output_ok)
                })()) })
            }fn wire__crate__api__panel_api__update_panel_credentials_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "update_panel_credentials", port: None, mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_username = <String>::sse_decode(&mut deserializer);
let api_password = <String>::sse_decode(&mut deserializer);deserializer.end();
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || {
                     let output_ok = crate::api::panel_api::update_panel_credentials(api_username, api_password)?;   Ok(output_ok)
                })()) })
            }

// Section: dart2rust


                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::api::panel_api::ConfigSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_path = <String>::sse_decode(deserializer);
let mut var_raw = <String>::sse_decode(deserializer);
let mut var_structured = <crate::api::panel_api::StructuredConfig>::sse_decode(deserializer);
let mut var_updatedAt = <String>::sse_decode(deserializer);
let mut var_backupPath = <Option<String>>::sse_decode(deserializer);
return crate::api::panel_api::ConfigSnapshot{path: var_path, raw: var_raw, structured: var_structured, updated_at: var_updatedAt, backup_path: var_backupPath};}
                }
                
                impl SseDecode for crate::api::panel_api::CustomNetItem {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_name = <String>::sse_decode(deserializer);
let mut var_cidr = <String>::sse_decode(deserializer);
return crate::api::panel_api::CustomNetItem{name: var_name, cidr: var_cidr};}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<String>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::panel_api::CustomNetItem> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::panel_api::CustomNetItem>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::api::panel_api::LogSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_lines = <Vec<String>>::sse_decode(deserializer);
let mut var_requested = <u32>::sse_decode(deserializer);
let mut var_path = <String>::sse_decode(deserializer);
let mut var_exists = <bool>::sse_decode(deserializer);
return crate::api::panel_api::LogSnapshot{lines: var_lines, requested: var_requested, path: var_path, exists: var_exists};}
                }
                
                impl SseDecode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<String>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for Option<crate::api::panel_api::ServiceProcessInfo> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<crate::api::panel_api::ServiceProcessInfo>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for crate::api::panel_api::PanelAccountSummary {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_username = <String>::sse_decode(deserializer);
let mut var_updatedAt = <String>::sse_decode(deserializer);
let mut var_credentialsPath = <String>::sse_decode(deserializer);
let mut var_requiresPasswordChange = <bool>::sse_decode(deserializer);
return crate::api::panel_api::PanelAccountSummary{username: var_username, updated_at: var_updatedAt, credentials_path: var_credentialsPath, requires_password_change: var_requiresPasswordChange};}
                }
                
                impl SseDecode for crate::api::panel_api::PanelSession {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_authenticated = <bool>::sse_decode(deserializer);
let mut var_user = <Option<String>>::sse_decode(deserializer);
return crate::api::panel_api::PanelSession{authenticated: var_authenticated, user: var_user};}
                }
                
                impl SseDecode for crate::api::panel_api::ServiceDetection {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_installed = <bool>::sse_decode(deserializer);
let mut var_runtimeReady = <bool>::sse_decode(deserializer);
let mut var_runtimeIssue = <String>::sse_decode(deserializer);
let mut var_serviceName = <String>::sse_decode(deserializer);
let mut var_installDir = <String>::sse_decode(deserializer);
let mut var_configPath = <String>::sse_decode(deserializer);
let mut var_logPath = <String>::sse_decode(deserializer);
let mut var_executablePath = <String>::sse_decode(deserializer);
let mut var_commandLine = <String>::sse_decode(deserializer);
let mut var_bundledExecutablePath = <String>::sse_decode(deserializer);
let mut var_bundledConfigPath = <String>::sse_decode(deserializer);
return crate::api::panel_api::ServiceDetection{installed: var_installed, runtime_ready: var_runtimeReady, runtime_issue: var_runtimeIssue, service_name: var_serviceName, install_dir: var_installDir, config_path: var_configPath, log_path: var_logPath, executable_path: var_executablePath, command_line: var_commandLine, bundled_executable_path: var_bundledExecutablePath, bundled_config_path: var_bundledConfigPath};}
                }
                
                impl SseDecode for crate::api::panel_api::ServiceOverview {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_detection = <crate::api::panel_api::ServiceDetection>::sse_decode(deserializer);
let mut var_status = <crate::api::panel_api::ServiceStatus>::sse_decode(deserializer);
let mut var_summaryEndpoints = <String>::sse_decode(deserializer);
return crate::api::panel_api::ServiceOverview{detection: var_detection, status: var_status, summary_endpoints: var_summaryEndpoints};}
                }
                
                impl SseDecode for crate::api::panel_api::ServiceProcessInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_cpuDisplay = <String>::sse_decode(deserializer);
let mut var_memoryDisplay = <String>::sse_decode(deserializer);
let mut var_elapsed = <String>::sse_decode(deserializer);
let mut var_command = <String>::sse_decode(deserializer);
return crate::api::panel_api::ServiceProcessInfo{cpu_display: var_cpuDisplay, memory_display: var_memoryDisplay, elapsed: var_elapsed, command: var_command};}
                }
                
                impl SseDecode for crate::api::panel_api::ServiceStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_serviceName = <String>::sse_decode(deserializer);
let mut var_description = <String>::sse_decode(deserializer);
let mut var_loadState = <String>::sse_decode(deserializer);
let mut var_activeState = <String>::sse_decode(deserializer);
let mut var_subState = <String>::sse_decode(deserializer);
let mut var_unitFileState = <String>::sse_decode(deserializer);
let mut var_pid = <u64>::sse_decode(deserializer);
let mut var_mainCode = <String>::sse_decode(deserializer);
let mut var_mainStatus = <String>::sse_decode(deserializer);
let mut var_activeSince = <String>::sse_decode(deserializer);
let mut var_fragmentPath = <String>::sse_decode(deserializer);
let mut var_isActive = <bool>::sse_decode(deserializer);
let mut var_installed = <bool>::sse_decode(deserializer);
let mut var_process = <Option<crate::api::panel_api::ServiceProcessInfo>>::sse_decode(deserializer);
return crate::api::panel_api::ServiceStatus{service_name: var_serviceName, description: var_description, load_state: var_loadState, active_state: var_activeState, sub_state: var_subState, unit_file_state: var_unitFileState, pid: var_pid, main_code: var_mainCode, main_status: var_mainStatus, active_since: var_activeSince, fragment_path: var_fragmentPath, is_active: var_isActive, installed: var_installed, process: var_process};}
                }
                
                impl SseDecode for crate::api::panel_api::StructuredConfig {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_tcpBind = <String>::sse_decode(deserializer);
let mut var_quicBind = <String>::sse_decode(deserializer);
let mut var_wsBind = <String>::sse_decode(deserializer);
let mut var_network = <String>::sse_decode(deserializer);
let mut var_whiteList = <Vec<String>>::sse_decode(deserializer);
let mut var_leaseDuration = <i64>::sse_decode(deserializer);
let mut var_webBind = <String>::sse_decode(deserializer);
let mut var_username = <String>::sse_decode(deserializer);
let mut var_password = <String>::sse_decode(deserializer);
let mut var_persistence = <bool>::sse_decode(deserializer);
let mut var_cert = <String>::sse_decode(deserializer);
let mut var_key = <String>::sse_decode(deserializer);
let mut var_serverQuicBind = <String>::sse_decode(deserializer);
let mut var_peerServers = <Vec<String>>::sse_decode(deserializer);
let mut var_serverToken = <String>::sse_decode(deserializer);
let mut var_customNets = <Vec<crate::api::panel_api::CustomNetItem>>::sse_decode(deserializer);
return crate::api::panel_api::StructuredConfig{tcp_bind: var_tcpBind, quic_bind: var_quicBind, ws_bind: var_wsBind, network: var_network, white_list: var_whiteList, lease_duration: var_leaseDuration, web_bind: var_webBind, username: var_username, password: var_password, persistence: var_persistence, cert: var_cert, key: var_key, server_quic_bind: var_serverQuicBind, peer_servers: var_peerServers, server_token: var_serverToken, custom_nets: var_customNets};}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__panel_api__config_snapshot_default_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__api__panel_api__custom_net_item_default_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__api__panel_api__init_app_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__api__panel_api__log_snapshot_default_impl(port, ptr, rust_vec_len, data_len),
14 => wire__crate__api__panel_api__panel_account_summary_default_impl(port, ptr, rust_vec_len, data_len),
15 => wire__crate__api__panel_api__panel_session_default_impl(port, ptr, rust_vec_len, data_len),
20 => wire__crate__api__panel_api__service_detection_default_impl(port, ptr, rust_vec_len, data_len),
21 => wire__crate__api__panel_api__service_overview_default_impl(port, ptr, rust_vec_len, data_len),
22 => wire__crate__api__panel_api__service_process_info_default_impl(port, ptr, rust_vec_len, data_len),
23 => wire__crate__api__panel_api__service_status_default_impl(port, ptr, rust_vec_len, data_len),
26 => wire__crate__api__panel_api__structured_config_default_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        3 => wire__crate__api__panel_api__detect_existing_service_impl(ptr, rust_vec_len, data_len),
4 => wire__crate__api__panel_api__get_panel_account_summary_impl(ptr, rust_vec_len, data_len),
5 => wire__crate__api__panel_api__get_service_overview_impl(ptr, rust_vec_len, data_len),
6 => wire__crate__api__panel_api__get_session_impl(ptr, rust_vec_len, data_len),
8 => wire__crate__api__panel_api__install_service_impl(ptr, rust_vec_len, data_len),
9 => wire__crate__api__panel_api__load_raw_config_impl(ptr, rust_vec_len, data_len),
10 => wire__crate__api__panel_api__load_structured_config_impl(ptr, rust_vec_len, data_len),
12 => wire__crate__api__panel_api__login_impl(ptr, rust_vec_len, data_len),
13 => wire__crate__api__panel_api__logout_impl(ptr, rust_vec_len, data_len),
16 => wire__crate__api__panel_api__read_log_tail_impl(ptr, rust_vec_len, data_len),
17 => wire__crate__api__panel_api__restart_service_impl(ptr, rust_vec_len, data_len),
18 => wire__crate__api__panel_api__save_raw_config_impl(ptr, rust_vec_len, data_len),
19 => wire__crate__api__panel_api__save_structured_config_impl(ptr, rust_vec_len, data_len),
24 => wire__crate__api__panel_api__start_service_impl(ptr, rust_vec_len, data_len),
25 => wire__crate__api__panel_api__stop_service_impl(ptr, rust_vec_len, data_len),
27 => wire__crate__api__panel_api__uninstall_service_impl(ptr, rust_vec_len, data_len),
28 => wire__crate__api__panel_api__update_panel_credentials_impl(ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::ConfigSnapshot {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.path.into_into_dart().into_dart(),
self.raw.into_into_dart().into_dart(),
self.structured.into_into_dart().into_dart(),
self.updated_at.into_into_dart().into_dart(),
self.backup_path.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::ConfigSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::ConfigSnapshot> for crate::api::panel_api::ConfigSnapshot {
            fn into_into_dart(self) -> crate::api::panel_api::ConfigSnapshot {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::CustomNetItem {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.name.into_into_dart().into_dart(),
self.cidr.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::CustomNetItem {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::CustomNetItem> for crate::api::panel_api::CustomNetItem {
            fn into_into_dart(self) -> crate::api::panel_api::CustomNetItem {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::LogSnapshot {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.lines.into_into_dart().into_dart(),
self.requested.into_into_dart().into_dart(),
self.path.into_into_dart().into_dart(),
self.exists.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::LogSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::LogSnapshot> for crate::api::panel_api::LogSnapshot {
            fn into_into_dart(self) -> crate::api::panel_api::LogSnapshot {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::PanelAccountSummary {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.username.into_into_dart().into_dart(),
self.updated_at.into_into_dart().into_dart(),
self.credentials_path.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::PanelAccountSummary {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::PanelAccountSummary> for crate::api::panel_api::PanelAccountSummary {
            fn into_into_dart(self) -> crate::api::panel_api::PanelAccountSummary {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::PanelSession {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.authenticated.into_into_dart().into_dart(),
self.user.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::PanelSession {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::PanelSession> for crate::api::panel_api::PanelSession {
            fn into_into_dart(self) -> crate::api::panel_api::PanelSession {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::ServiceDetection {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.installed.into_into_dart().into_dart(),
self.service_name.into_into_dart().into_dart(),
self.install_dir.into_into_dart().into_dart(),
self.config_path.into_into_dart().into_dart(),
self.log_path.into_into_dart().into_dart(),
self.executable_path.into_into_dart().into_dart(),
self.command_line.into_into_dart().into_dart(),
self.bundled_executable_path.into_into_dart().into_dart(),
self.bundled_config_path.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::ServiceDetection {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::ServiceDetection> for crate::api::panel_api::ServiceDetection {
            fn into_into_dart(self) -> crate::api::panel_api::ServiceDetection {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::ServiceOverview {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.detection.into_into_dart().into_dart(),
self.status.into_into_dart().into_dart(),
self.summary_endpoints.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::ServiceOverview {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::ServiceOverview> for crate::api::panel_api::ServiceOverview {
            fn into_into_dart(self) -> crate::api::panel_api::ServiceOverview {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::ServiceProcessInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.cpu_display.into_into_dart().into_dart(),
self.memory_display.into_into_dart().into_dart(),
self.elapsed.into_into_dart().into_dart(),
self.command.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::ServiceProcessInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::ServiceProcessInfo> for crate::api::panel_api::ServiceProcessInfo {
            fn into_into_dart(self) -> crate::api::panel_api::ServiceProcessInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::ServiceStatus {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.service_name.into_into_dart().into_dart(),
self.description.into_into_dart().into_dart(),
self.load_state.into_into_dart().into_dart(),
self.active_state.into_into_dart().into_dart(),
self.sub_state.into_into_dart().into_dart(),
self.unit_file_state.into_into_dart().into_dart(),
self.pid.into_into_dart().into_dart(),
self.main_code.into_into_dart().into_dart(),
self.main_status.into_into_dart().into_dart(),
self.active_since.into_into_dart().into_dart(),
self.fragment_path.into_into_dart().into_dart(),
self.is_active.into_into_dart().into_dart(),
self.installed.into_into_dart().into_dart(),
self.process.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::ServiceStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::ServiceStatus> for crate::api::panel_api::ServiceStatus {
            fn into_into_dart(self) -> crate::api::panel_api::ServiceStatus {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::panel_api::StructuredConfig {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.tcp_bind.into_into_dart().into_dart(),
self.quic_bind.into_into_dart().into_dart(),
self.ws_bind.into_into_dart().into_dart(),
self.network.into_into_dart().into_dart(),
self.white_list.into_into_dart().into_dart(),
self.lease_duration.into_into_dart().into_dart(),
self.web_bind.into_into_dart().into_dart(),
self.username.into_into_dart().into_dart(),
self.password.into_into_dart().into_dart(),
self.persistence.into_into_dart().into_dart(),
self.cert.into_into_dart().into_dart(),
self.key.into_into_dart().into_dart(),
self.server_quic_bind.into_into_dart().into_dart(),
self.peer_servers.into_into_dart().into_dart(),
self.server_token.into_into_dart().into_dart(),
self.custom_nets.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::panel_api::StructuredConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::panel_api::StructuredConfig> for crate::api::panel_api::StructuredConfig {
            fn into_into_dart(self) -> crate::api::panel_api::StructuredConfig {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::api::panel_api::ConfigSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.path, serializer);
<String>::sse_encode(self.raw, serializer);
<crate::api::panel_api::StructuredConfig>::sse_encode(self.structured, serializer);
<String>::sse_encode(self.updated_at, serializer);
<Option<String>>::sse_encode(self.backup_path, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::CustomNetItem {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.name, serializer);
<String>::sse_encode(self.cidr, serializer);}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <String>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::panel_api::CustomNetItem> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::panel_api::CustomNetItem>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::api::panel_api::LogSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<String>>::sse_encode(self.lines, serializer);
<u32>::sse_encode(self.requested, serializer);
<String>::sse_encode(self.path, serializer);
<bool>::sse_encode(self.exists, serializer);}
                }
                
                impl SseEncode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <String>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for Option<crate::api::panel_api::ServiceProcessInfo> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <crate::api::panel_api::ServiceProcessInfo>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for crate::api::panel_api::PanelAccountSummary {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.username, serializer);
<String>::sse_encode(self.updated_at, serializer);
<String>::sse_encode(self.credentials_path, serializer);
<bool>::sse_encode(self.requires_password_change, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::PanelSession {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.authenticated, serializer);
<Option<String>>::sse_encode(self.user, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::ServiceDetection {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.installed, serializer);
<bool>::sse_encode(self.runtime_ready, serializer);
<String>::sse_encode(self.runtime_issue, serializer);
<String>::sse_encode(self.service_name, serializer);
<String>::sse_encode(self.install_dir, serializer);
<String>::sse_encode(self.config_path, serializer);
<String>::sse_encode(self.log_path, serializer);
<String>::sse_encode(self.executable_path, serializer);
<String>::sse_encode(self.command_line, serializer);
<String>::sse_encode(self.bundled_executable_path, serializer);
<String>::sse_encode(self.bundled_config_path, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::ServiceOverview {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::api::panel_api::ServiceDetection>::sse_encode(self.detection, serializer);
<crate::api::panel_api::ServiceStatus>::sse_encode(self.status, serializer);
<String>::sse_encode(self.summary_endpoints, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::ServiceProcessInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.cpu_display, serializer);
<String>::sse_encode(self.memory_display, serializer);
<String>::sse_encode(self.elapsed, serializer);
<String>::sse_encode(self.command, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::ServiceStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.service_name, serializer);
<String>::sse_encode(self.description, serializer);
<String>::sse_encode(self.load_state, serializer);
<String>::sse_encode(self.active_state, serializer);
<String>::sse_encode(self.sub_state, serializer);
<String>::sse_encode(self.unit_file_state, serializer);
<u64>::sse_encode(self.pid, serializer);
<String>::sse_encode(self.main_code, serializer);
<String>::sse_encode(self.main_status, serializer);
<String>::sse_encode(self.active_since, serializer);
<String>::sse_encode(self.fragment_path, serializer);
<bool>::sse_encode(self.is_active, serializer);
<bool>::sse_encode(self.installed, serializer);
<Option<crate::api::panel_api::ServiceProcessInfo>>::sse_encode(self.process, serializer);}
                }
                
                impl SseEncode for crate::api::panel_api::StructuredConfig {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.tcp_bind, serializer);
<String>::sse_encode(self.quic_bind, serializer);
<String>::sse_encode(self.ws_bind, serializer);
<String>::sse_encode(self.network, serializer);
<Vec<String>>::sse_encode(self.white_list, serializer);
<i64>::sse_encode(self.lease_duration, serializer);
<String>::sse_encode(self.web_bind, serializer);
<String>::sse_encode(self.username, serializer);
<String>::sse_encode(self.password, serializer);
<bool>::sse_encode(self.persistence, serializer);
<String>::sse_encode(self.cert, serializer);
<String>::sse_encode(self.key, serializer);
<String>::sse_encode(self.server_quic_bind, serializer);
<Vec<String>>::sse_encode(self.peer_servers, serializer);
<String>::sse_encode(self.server_token, serializer);
<Vec<crate::api::panel_api::CustomNetItem>>::sse_encode(self.custom_nets, serializer);}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        
