// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/panel_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiPanelApiInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.1.0';

                  @override
                  int get rustContentHash => -541507629;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'rust_lib_vnt_app',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<ConfigSnapshot> crateApiPanelApiConfigSnapshotDefault();

Future<CustomNetItem> crateApiPanelApiCustomNetItemDefault();

ServiceDetection crateApiPanelApiDetectExistingService();

PanelAccountSummary crateApiPanelApiGetPanelAccountSummary();

ServiceOverview crateApiPanelApiGetServiceOverview();

PanelSession crateApiPanelApiGetSession();

Future<void> crateApiPanelApiInitApp();

ServiceOverview crateApiPanelApiInstallService({required String targetDir });

ConfigSnapshot crateApiPanelApiLoadRawConfig();

ConfigSnapshot crateApiPanelApiLoadStructuredConfig();

Future<LogSnapshot> crateApiPanelApiLogSnapshotDefault();

PanelSession crateApiPanelApiLogin({required String username , required String password });

PanelSession crateApiPanelApiLogout();

Future<PanelAccountSummary> crateApiPanelApiPanelAccountSummaryDefault();

Future<PanelSession> crateApiPanelApiPanelSessionDefault();

LogSnapshot crateApiPanelApiReadLogTail({required int lines });

ServiceOverview crateApiPanelApiRestartService();

ConfigSnapshot crateApiPanelApiSaveRawConfig({required String raw , required bool restart });

ConfigSnapshot crateApiPanelApiSaveStructuredConfig({required StructuredConfig payload , required bool restart });

Future<ServiceDetection> crateApiPanelApiServiceDetectionDefault();

Future<ServiceOverview> crateApiPanelApiServiceOverviewDefault();

Future<ServiceProcessInfo> crateApiPanelApiServiceProcessInfoDefault();

Future<ServiceStatus> crateApiPanelApiServiceStatusDefault();

ServiceOverview crateApiPanelApiStartService();

ServiceOverview crateApiPanelApiStopService();

Future<StructuredConfig> crateApiPanelApiStructuredConfigDefault();

ServiceOverview crateApiPanelApiUninstallService();

PanelAccountSummary crateApiPanelApiUpdatePanelCredentials({required String username , required String password });


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<ConfigSnapshot> crateApiPanelApiConfigSnapshotDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiConfigSnapshotDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiConfigSnapshotDefaultConstMeta => const TaskConstMeta(
            debugName: "config_snapshot_default",
            argNames: [],
        );
        

@override Future<CustomNetItem> crateApiPanelApiCustomNetItemDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_custom_net_item,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiCustomNetItemDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiCustomNetItemDefaultConstMeta => const TaskConstMeta(
            debugName: "custom_net_item_default",
            argNames: [],
        );
        

@override ServiceDetection crateApiPanelApiDetectExistingService()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_detection,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiDetectExistingServiceConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiDetectExistingServiceConstMeta => const TaskConstMeta(
            debugName: "detect_existing_service",
            argNames: [],
        );
        

@override PanelAccountSummary crateApiPanelApiGetPanelAccountSummary()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_account_summary,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiGetPanelAccountSummaryConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiGetPanelAccountSummaryConstMeta => const TaskConstMeta(
            debugName: "get_panel_account_summary",
            argNames: [],
        );
        

@override ServiceOverview crateApiPanelApiGetServiceOverview()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiGetServiceOverviewConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiGetServiceOverviewConstMeta => const TaskConstMeta(
            debugName: "get_service_overview",
            argNames: [],
        );
        

@override PanelSession crateApiPanelApiGetSession()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_session,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiGetSessionConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiGetSessionConstMeta => const TaskConstMeta(
            debugName: "get_session",
            argNames: [],
        );
        

@override Future<void> crateApiPanelApiInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override ServiceOverview crateApiPanelApiInstallService({required String targetDir })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(targetDir, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiInstallServiceConstMeta,
            argValues: [targetDir],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiInstallServiceConstMeta => const TaskConstMeta(
            debugName: "install_service",
            argNames: ["targetDir"],
        );
        

@override ConfigSnapshot crateApiPanelApiLoadRawConfig()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiLoadRawConfigConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiLoadRawConfigConstMeta => const TaskConstMeta(
            debugName: "load_raw_config",
            argNames: [],
        );
        

@override ConfigSnapshot crateApiPanelApiLoadStructuredConfig()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiLoadStructuredConfigConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiLoadStructuredConfigConstMeta => const TaskConstMeta(
            debugName: "load_structured_config",
            argNames: [],
        );
        

@override Future<LogSnapshot> crateApiPanelApiLogSnapshotDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_log_snapshot,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiLogSnapshotDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiLogSnapshotDefaultConstMeta => const TaskConstMeta(
            debugName: "log_snapshot_default",
            argNames: [],
        );
        

@override PanelSession crateApiPanelApiLogin({required String username , required String password })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(username, serializer);
sse_encode_String(password, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_session,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiLoginConstMeta,
            argValues: [username, password],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiLoginConstMeta => const TaskConstMeta(
            debugName: "login",
            argNames: ["username", "password"],
        );
        

@override PanelSession crateApiPanelApiLogout()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_session,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiLogoutConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiLogoutConstMeta => const TaskConstMeta(
            debugName: "logout",
            argNames: [],
        );
        

@override Future<PanelAccountSummary> crateApiPanelApiPanelAccountSummaryDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_account_summary,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiPanelAccountSummaryDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiPanelAccountSummaryDefaultConstMeta => const TaskConstMeta(
            debugName: "panel_account_summary_default",
            argNames: [],
        );
        

@override Future<PanelSession> crateApiPanelApiPanelSessionDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_session,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiPanelSessionDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiPanelSessionDefaultConstMeta => const TaskConstMeta(
            debugName: "panel_session_default",
            argNames: [],
        );
        

@override LogSnapshot crateApiPanelApiReadLogTail({required int lines })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_32(lines, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_log_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiReadLogTailConstMeta,
            argValues: [lines],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiReadLogTailConstMeta => const TaskConstMeta(
            debugName: "read_log_tail",
            argNames: ["lines"],
        );
        

@override ServiceOverview crateApiPanelApiRestartService()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiRestartServiceConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiRestartServiceConstMeta => const TaskConstMeta(
            debugName: "restart_service",
            argNames: [],
        );
        

@override ConfigSnapshot crateApiPanelApiSaveRawConfig({required String raw , required bool restart })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(raw, serializer);
sse_encode_bool(restart, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiSaveRawConfigConstMeta,
            argValues: [raw, restart],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiSaveRawConfigConstMeta => const TaskConstMeta(
            debugName: "save_raw_config",
            argNames: ["raw", "restart"],
        );
        

@override ConfigSnapshot crateApiPanelApiSaveStructuredConfig({required StructuredConfig payload , required bool restart })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_structured_config(payload, serializer);
sse_encode_bool(restart, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiSaveStructuredConfigConstMeta,
            argValues: [payload, restart],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiSaveStructuredConfigConstMeta => const TaskConstMeta(
            debugName: "save_structured_config",
            argNames: ["payload", "restart"],
        );
        

@override Future<ServiceDetection> crateApiPanelApiServiceDetectionDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_detection,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiServiceDetectionDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiServiceDetectionDefaultConstMeta => const TaskConstMeta(
            debugName: "service_detection_default",
            argNames: [],
        );
        

@override Future<ServiceOverview> crateApiPanelApiServiceOverviewDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiServiceOverviewDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiServiceOverviewDefaultConstMeta => const TaskConstMeta(
            debugName: "service_overview_default",
            argNames: [],
        );
        

@override Future<ServiceProcessInfo> crateApiPanelApiServiceProcessInfoDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_process_info,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiServiceProcessInfoDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiServiceProcessInfoDefaultConstMeta => const TaskConstMeta(
            debugName: "service_process_info_default",
            argNames: [],
        );
        

@override Future<ServiceStatus> crateApiPanelApiServiceStatusDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_status,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiServiceStatusDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiServiceStatusDefaultConstMeta => const TaskConstMeta(
            debugName: "service_status_default",
            argNames: [],
        );
        

@override ServiceOverview crateApiPanelApiStartService()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiStartServiceConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiStartServiceConstMeta => const TaskConstMeta(
            debugName: "start_service",
            argNames: [],
        );
        

@override ServiceOverview crateApiPanelApiStopService()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiStopServiceConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiStopServiceConstMeta => const TaskConstMeta(
            debugName: "stop_service",
            argNames: [],
        );
        

@override Future<StructuredConfig> crateApiPanelApiStructuredConfigDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_structured_config,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiPanelApiStructuredConfigDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiStructuredConfigDefaultConstMeta => const TaskConstMeta(
            debugName: "structured_config_default",
            argNames: [],
        );
        

@override ServiceOverview crateApiPanelApiUninstallService()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_service_overview,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiUninstallServiceConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiUninstallServiceConstMeta => const TaskConstMeta(
            debugName: "uninstall_service",
            argNames: [],
        );
        

@override PanelAccountSummary crateApiPanelApiUpdatePanelCredentials({required String username , required String password })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(username, serializer);
sse_encode_String(password, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_panel_account_summary,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiPanelApiUpdatePanelCredentialsConstMeta,
            argValues: [username, password],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiPanelApiUpdatePanelCredentialsConstMeta => const TaskConstMeta(
            debugName: "update_panel_credentials",
            argNames: ["username", "password"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected ServiceProcessInfo dco_decode_box_autoadd_service_process_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_service_process_info(raw); }

@protected StructuredConfig dco_decode_box_autoadd_structured_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_structured_config(raw); }

@protected ConfigSnapshot dco_decode_config_snapshot(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return ConfigSnapshot(path: dco_decode_String(arr[0]),
raw: dco_decode_String(arr[1]),
structured: dco_decode_structured_config(arr[2]),
updatedAt: dco_decode_String(arr[3]),
backupPath: dco_decode_opt_String(arr[4]),); }

@protected CustomNetItem dco_decode_custom_net_item(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return CustomNetItem(name: dco_decode_String(arr[0]),
cidr: dco_decode_String(arr[1]),); }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<CustomNetItem> dco_decode_list_custom_net_item(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_custom_net_item).toList(); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected LogSnapshot dco_decode_log_snapshot(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return LogSnapshot(lines: dco_decode_list_String(arr[0]),
requested: dco_decode_u_32(arr[1]),
path: dco_decode_String(arr[2]),
exists: dco_decode_bool(arr[3]),); }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected ServiceProcessInfo? dco_decode_opt_box_autoadd_service_process_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_box_autoadd_service_process_info(raw); }

@protected PanelAccountSummary dco_decode_panel_account_summary(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return PanelAccountSummary(username: dco_decode_String(arr[0]),
updatedAt: dco_decode_String(arr[1]),
credentialsPath: dco_decode_String(arr[2]),
requiresPasswordChange: dco_decode_bool(arr[3]),); }

@protected PanelSession dco_decode_panel_session(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return PanelSession(authenticated: dco_decode_bool(arr[0]),
user: dco_decode_opt_String(arr[1]),); }

@protected ServiceDetection dco_decode_service_detection(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 11) throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
                return ServiceDetection(installed: dco_decode_bool(arr[0]),
runtimeReady: dco_decode_bool(arr[1]),
runtimeIssue: dco_decode_String(arr[2]),
serviceName: dco_decode_String(arr[3]),
installDir: dco_decode_String(arr[4]),
configPath: dco_decode_String(arr[5]),
logPath: dco_decode_String(arr[6]),
executablePath: dco_decode_String(arr[7]),
commandLine: dco_decode_String(arr[8]),
bundledExecutablePath: dco_decode_String(arr[9]),
bundledConfigPath: dco_decode_String(arr[10]),); }

@protected ServiceOverview dco_decode_service_overview(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return ServiceOverview(detection: dco_decode_service_detection(arr[0]),
status: dco_decode_service_status(arr[1]),
summaryEndpoints: dco_decode_String(arr[2]),); }

@protected ServiceProcessInfo dco_decode_service_process_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return ServiceProcessInfo(cpuDisplay: dco_decode_String(arr[0]),
memoryDisplay: dco_decode_String(arr[1]),
elapsed: dco_decode_String(arr[2]),
command: dco_decode_String(arr[3]),); }

@protected ServiceStatus dco_decode_service_status(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 14) throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
                return ServiceStatus(serviceName: dco_decode_String(arr[0]),
description: dco_decode_String(arr[1]),
loadState: dco_decode_String(arr[2]),
activeState: dco_decode_String(arr[3]),
subState: dco_decode_String(arr[4]),
unitFileState: dco_decode_String(arr[5]),
pid: dco_decode_u_64(arr[6]),
mainCode: dco_decode_String(arr[7]),
mainStatus: dco_decode_String(arr[8]),
activeSince: dco_decode_String(arr[9]),
fragmentPath: dco_decode_String(arr[10]),
isActive: dco_decode_bool(arr[11]),
installed: dco_decode_bool(arr[12]),
process: dco_decode_opt_box_autoadd_service_process_info(arr[13]),); }

@protected StructuredConfig dco_decode_structured_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 16) throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
                return StructuredConfig(tcpBind: dco_decode_String(arr[0]),
quicBind: dco_decode_String(arr[1]),
wsBind: dco_decode_String(arr[2]),
network: dco_decode_String(arr[3]),
whiteList: dco_decode_list_String(arr[4]),
leaseDuration: dco_decode_i_64(arr[5]),
webBind: dco_decode_String(arr[6]),
username: dco_decode_String(arr[7]),
password: dco_decode_String(arr[8]),
persistence: dco_decode_bool(arr[9]),
cert: dco_decode_String(arr[10]),
key: dco_decode_String(arr[11]),
serverQuicBind: dco_decode_String(arr[12]),
peerServers: dco_decode_list_String(arr[13]),
serverToken: dco_decode_String(arr[14]),
customNets: dco_decode_list_custom_net_item(arr[15]),); }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected ServiceProcessInfo sse_decode_box_autoadd_service_process_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_service_process_info(deserializer)); }

@protected StructuredConfig sse_decode_box_autoadd_structured_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_structured_config(deserializer)); }

@protected ConfigSnapshot sse_decode_config_snapshot(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_path = sse_decode_String(deserializer);
var var_raw = sse_decode_String(deserializer);
var var_structured = sse_decode_structured_config(deserializer);
var var_updatedAt = sse_decode_String(deserializer);
var var_backupPath = sse_decode_opt_String(deserializer);
return ConfigSnapshot(path: var_path, raw: var_raw, structured: var_structured, updatedAt: var_updatedAt, backupPath: var_backupPath); }

@protected CustomNetItem sse_decode_custom_net_item(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_name = sse_decode_String(deserializer);
var var_cidr = sse_decode_String(deserializer);
return CustomNetItem(name: var_name, cidr: var_cidr); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<CustomNetItem> sse_decode_list_custom_net_item(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <CustomNetItem>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_custom_net_item(deserializer)); }
        return ans_;
         }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected LogSnapshot sse_decode_log_snapshot(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_lines = sse_decode_list_String(deserializer);
var var_requested = sse_decode_u_32(deserializer);
var var_path = sse_decode_String(deserializer);
var var_exists = sse_decode_bool(deserializer);
return LogSnapshot(lines: var_lines, requested: var_requested, path: var_path, exists: var_exists); }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected ServiceProcessInfo? sse_decode_opt_box_autoadd_service_process_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_box_autoadd_service_process_info(deserializer));
            } else {
                return null;
            }
             }

@protected PanelAccountSummary sse_decode_panel_account_summary(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_username = sse_decode_String(deserializer);
var var_updatedAt = sse_decode_String(deserializer);
var var_credentialsPath = sse_decode_String(deserializer);
var var_requiresPasswordChange = sse_decode_bool(deserializer);
return PanelAccountSummary(username: var_username, updatedAt: var_updatedAt, credentialsPath: var_credentialsPath, requiresPasswordChange: var_requiresPasswordChange); }

@protected PanelSession sse_decode_panel_session(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_authenticated = sse_decode_bool(deserializer);
var var_user = sse_decode_opt_String(deserializer);
return PanelSession(authenticated: var_authenticated, user: var_user); }

@protected ServiceDetection sse_decode_service_detection(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_installed = sse_decode_bool(deserializer);
var var_runtimeReady = sse_decode_bool(deserializer);
var var_runtimeIssue = sse_decode_String(deserializer);
var var_serviceName = sse_decode_String(deserializer);
var var_installDir = sse_decode_String(deserializer);
var var_configPath = sse_decode_String(deserializer);
var var_logPath = sse_decode_String(deserializer);
var var_executablePath = sse_decode_String(deserializer);
var var_commandLine = sse_decode_String(deserializer);
var var_bundledExecutablePath = sse_decode_String(deserializer);
var var_bundledConfigPath = sse_decode_String(deserializer);
return ServiceDetection(installed: var_installed, runtimeReady: var_runtimeReady, runtimeIssue: var_runtimeIssue, serviceName: var_serviceName, installDir: var_installDir, configPath: var_configPath, logPath: var_logPath, executablePath: var_executablePath, commandLine: var_commandLine, bundledExecutablePath: var_bundledExecutablePath, bundledConfigPath: var_bundledConfigPath); }

@protected ServiceOverview sse_decode_service_overview(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_detection = sse_decode_service_detection(deserializer);
var var_status = sse_decode_service_status(deserializer);
var var_summaryEndpoints = sse_decode_String(deserializer);
return ServiceOverview(detection: var_detection, status: var_status, summaryEndpoints: var_summaryEndpoints); }

@protected ServiceProcessInfo sse_decode_service_process_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_cpuDisplay = sse_decode_String(deserializer);
var var_memoryDisplay = sse_decode_String(deserializer);
var var_elapsed = sse_decode_String(deserializer);
var var_command = sse_decode_String(deserializer);
return ServiceProcessInfo(cpuDisplay: var_cpuDisplay, memoryDisplay: var_memoryDisplay, elapsed: var_elapsed, command: var_command); }

@protected ServiceStatus sse_decode_service_status(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_serviceName = sse_decode_String(deserializer);
var var_description = sse_decode_String(deserializer);
var var_loadState = sse_decode_String(deserializer);
var var_activeState = sse_decode_String(deserializer);
var var_subState = sse_decode_String(deserializer);
var var_unitFileState = sse_decode_String(deserializer);
var var_pid = sse_decode_u_64(deserializer);
var var_mainCode = sse_decode_String(deserializer);
var var_mainStatus = sse_decode_String(deserializer);
var var_activeSince = sse_decode_String(deserializer);
var var_fragmentPath = sse_decode_String(deserializer);
var var_isActive = sse_decode_bool(deserializer);
var var_installed = sse_decode_bool(deserializer);
var var_process = sse_decode_opt_box_autoadd_service_process_info(deserializer);
return ServiceStatus(serviceName: var_serviceName, description: var_description, loadState: var_loadState, activeState: var_activeState, subState: var_subState, unitFileState: var_unitFileState, pid: var_pid, mainCode: var_mainCode, mainStatus: var_mainStatus, activeSince: var_activeSince, fragmentPath: var_fragmentPath, isActive: var_isActive, installed: var_installed, process: var_process); }

@protected StructuredConfig sse_decode_structured_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_tcpBind = sse_decode_String(deserializer);
var var_quicBind = sse_decode_String(deserializer);
var var_wsBind = sse_decode_String(deserializer);
var var_network = sse_decode_String(deserializer);
var var_whiteList = sse_decode_list_String(deserializer);
var var_leaseDuration = sse_decode_i_64(deserializer);
var var_webBind = sse_decode_String(deserializer);
var var_username = sse_decode_String(deserializer);
var var_password = sse_decode_String(deserializer);
var var_persistence = sse_decode_bool(deserializer);
var var_cert = sse_decode_String(deserializer);
var var_key = sse_decode_String(deserializer);
var var_serverQuicBind = sse_decode_String(deserializer);
var var_peerServers = sse_decode_list_String(deserializer);
var var_serverToken = sse_decode_String(deserializer);
var var_customNets = sse_decode_list_custom_net_item(deserializer);
return StructuredConfig(tcpBind: var_tcpBind, quicBind: var_quicBind, wsBind: var_wsBind, network: var_network, whiteList: var_whiteList, leaseDuration: var_leaseDuration, webBind: var_webBind, username: var_username, password: var_password, persistence: var_persistence, cert: var_cert, key: var_key, serverQuicBind: var_serverQuicBind, peerServers: var_peerServers, serverToken: var_serverToken, customNets: var_customNets); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_service_process_info(ServiceProcessInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_service_process_info(self, serializer); }

@protected void sse_encode_box_autoadd_structured_config(StructuredConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_structured_config(self, serializer); }

@protected void sse_encode_config_snapshot(ConfigSnapshot self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.path, serializer);
sse_encode_String(self.raw, serializer);
sse_encode_structured_config(self.structured, serializer);
sse_encode_String(self.updatedAt, serializer);
sse_encode_opt_String(self.backupPath, serializer);
 }

@protected void sse_encode_custom_net_item(CustomNetItem self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.name, serializer);
sse_encode_String(self.cidr, serializer);
 }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_custom_net_item(List<CustomNetItem> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_custom_net_item(item, serializer); } }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_log_snapshot(LogSnapshot self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_String(self.lines, serializer);
sse_encode_u_32(self.requested, serializer);
sse_encode_String(self.path, serializer);
sse_encode_bool(self.exists, serializer);
 }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_opt_box_autoadd_service_process_info(ServiceProcessInfo? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_box_autoadd_service_process_info(self, serializer);
                }
                 }

@protected void sse_encode_panel_account_summary(PanelAccountSummary self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.username, serializer);
sse_encode_String(self.updatedAt, serializer);
sse_encode_String(self.credentialsPath, serializer);
sse_encode_bool(self.requiresPasswordChange, serializer);
 }

@protected void sse_encode_panel_session(PanelSession self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_bool(self.authenticated, serializer);
sse_encode_opt_String(self.user, serializer);
 }

@protected void sse_encode_service_detection(ServiceDetection self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_bool(self.installed, serializer);
sse_encode_bool(self.runtimeReady, serializer);
sse_encode_String(self.runtimeIssue, serializer);
sse_encode_String(self.serviceName, serializer);
sse_encode_String(self.installDir, serializer);
sse_encode_String(self.configPath, serializer);
sse_encode_String(self.logPath, serializer);
sse_encode_String(self.executablePath, serializer);
sse_encode_String(self.commandLine, serializer);
sse_encode_String(self.bundledExecutablePath, serializer);
sse_encode_String(self.bundledConfigPath, serializer);
 }

@protected void sse_encode_service_overview(ServiceOverview self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_service_detection(self.detection, serializer);
sse_encode_service_status(self.status, serializer);
sse_encode_String(self.summaryEndpoints, serializer);
 }

@protected void sse_encode_service_process_info(ServiceProcessInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.cpuDisplay, serializer);
sse_encode_String(self.memoryDisplay, serializer);
sse_encode_String(self.elapsed, serializer);
sse_encode_String(self.command, serializer);
 }

@protected void sse_encode_service_status(ServiceStatus self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.serviceName, serializer);
sse_encode_String(self.description, serializer);
sse_encode_String(self.loadState, serializer);
sse_encode_String(self.activeState, serializer);
sse_encode_String(self.subState, serializer);
sse_encode_String(self.unitFileState, serializer);
sse_encode_u_64(self.pid, serializer);
sse_encode_String(self.mainCode, serializer);
sse_encode_String(self.mainStatus, serializer);
sse_encode_String(self.activeSince, serializer);
sse_encode_String(self.fragmentPath, serializer);
sse_encode_bool(self.isActive, serializer);
sse_encode_bool(self.installed, serializer);
sse_encode_opt_box_autoadd_service_process_info(self.process, serializer);
 }

@protected void sse_encode_structured_config(StructuredConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.tcpBind, serializer);
sse_encode_String(self.quicBind, serializer);
sse_encode_String(self.wsBind, serializer);
sse_encode_String(self.network, serializer);
sse_encode_list_String(self.whiteList, serializer);
sse_encode_i_64(self.leaseDuration, serializer);
sse_encode_String(self.webBind, serializer);
sse_encode_String(self.username, serializer);
sse_encode_String(self.password, serializer);
sse_encode_bool(self.persistence, serializer);
sse_encode_String(self.cert, serializer);
sse_encode_String(self.key, serializer);
sse_encode_String(self.serverQuicBind, serializer);
sse_encode_list_String(self.peerServers, serializer);
sse_encode_String(self.serverToken, serializer);
sse_encode_list_custom_net_item(self.customNets, serializer);
 }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }
                }
                
