// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/panel_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected ServiceProcessInfo dco_decode_box_autoadd_service_process_info(dynamic raw);

@protected StructuredConfig dco_decode_box_autoadd_structured_config(dynamic raw);

@protected ConfigSnapshot dco_decode_config_snapshot(dynamic raw);

@protected CustomNetItem dco_decode_custom_net_item(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<CustomNetItem> dco_decode_list_custom_net_item(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected LogSnapshot dco_decode_log_snapshot(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected ServiceProcessInfo? dco_decode_opt_box_autoadd_service_process_info(dynamic raw);

@protected PanelAccountSummary dco_decode_panel_account_summary(dynamic raw);

@protected PanelSession dco_decode_panel_session(dynamic raw);

@protected ServiceDetection dco_decode_service_detection(dynamic raw);

@protected ServiceOverview dco_decode_service_overview(dynamic raw);

@protected ServiceProcessInfo dco_decode_service_process_info(dynamic raw);

@protected ServiceStatus dco_decode_service_status(dynamic raw);

@protected StructuredConfig dco_decode_structured_config(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected ServiceProcessInfo sse_decode_box_autoadd_service_process_info(SseDeserializer deserializer);

@protected StructuredConfig sse_decode_box_autoadd_structured_config(SseDeserializer deserializer);

@protected ConfigSnapshot sse_decode_config_snapshot(SseDeserializer deserializer);

@protected CustomNetItem sse_decode_custom_net_item(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<CustomNetItem> sse_decode_list_custom_net_item(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected LogSnapshot sse_decode_log_snapshot(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected ServiceProcessInfo? sse_decode_opt_box_autoadd_service_process_info(SseDeserializer deserializer);

@protected PanelAccountSummary sse_decode_panel_account_summary(SseDeserializer deserializer);

@protected PanelSession sse_decode_panel_session(SseDeserializer deserializer);

@protected ServiceDetection sse_decode_service_detection(SseDeserializer deserializer);

@protected ServiceOverview sse_decode_service_overview(SseDeserializer deserializer);

@protected ServiceProcessInfo sse_decode_service_process_info(SseDeserializer deserializer);

@protected ServiceStatus sse_decode_service_status(SseDeserializer deserializer);

@protected StructuredConfig sse_decode_structured_config(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_service_process_info(ServiceProcessInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_structured_config(StructuredConfig self, SseSerializer serializer);

@protected void sse_encode_config_snapshot(ConfigSnapshot self, SseSerializer serializer);

@protected void sse_encode_custom_net_item(CustomNetItem self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_custom_net_item(List<CustomNetItem> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_log_snapshot(LogSnapshot self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_service_process_info(ServiceProcessInfo? self, SseSerializer serializer);

@protected void sse_encode_panel_account_summary(PanelAccountSummary self, SseSerializer serializer);

@protected void sse_encode_panel_session(PanelSession self, SseSerializer serializer);

@protected void sse_encode_service_detection(ServiceDetection self, SseSerializer serializer);

@protected void sse_encode_service_overview(ServiceOverview self, SseSerializer serializer);

@protected void sse_encode_service_process_info(ServiceProcessInfo self, SseSerializer serializer);

@protected void sse_encode_service_status(ServiceStatus self, SseSerializer serializer);

@protected void sse_encode_structured_config(StructuredConfig self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
        }
        