// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `build_service_overview`, `build_start_failure_message`, `configure_no_window`, `credentials_path`, `current_exe_dir`, `default_install_dir`, `detect_service`, `direct_write_with_backup`, `elevated_write_with_backup`, `ensure_runtime_layout`, `format_system_time`, `inspect_runtime_layout`, `is_permission_error`, `load_config_snapshot_for_path`, `load_config_snapshot`, `load_or_initialize_credentials`, `now_string`, `parse_conf_path`, `parse_executable_path`, `parse_toml`, `persist_credentials`, `portable_data_root`, `ps_quote`, `push_optional_string`, `push_required_string`, `query_service_status`, `read_last_log_line`, `render_structured_config`, `requires_password_change`, `resolve_bundled_asset_source`, `resolve_bundled_file`, `run_elevated_powershell_file`, `run_powershell_json`, `run_powershell_script`, `run_service_action`, `run_standard_powershell_file`, `sanitize_string_list`, `split_windows_command_line`, `start_portable_process`, `stop_portable_process`, `structured_from_raw`, `summarize_endpoints`, `temp_file_path`, `validate_structured_config`, `verify_password`, `write_config_snapshot`, `write_with_backup`
// These types are ignored because they are not used by any `pub` functions: `RawConfigToml`, `RuntimeLayoutState`, `ServiceJsonProcess`, `ServiceJsonStatus`, `ServiceQuery`, `StoredCredentials`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`, `default`, `default`


            PanelSession getSession() => RustLib.instance.api.crateApiPanelApiGetSession();

PanelSession login({required String username , required String password }) => RustLib.instance.api.crateApiPanelApiLogin(username: username, password: password);

PanelSession logout() => RustLib.instance.api.crateApiPanelApiLogout();

PanelAccountSummary getPanelAccountSummary() => RustLib.instance.api.crateApiPanelApiGetPanelAccountSummary();

PanelAccountSummary updatePanelCredentials({required String username , required String password }) => RustLib.instance.api.crateApiPanelApiUpdatePanelCredentials(username: username, password: password);

ServiceDetection detectExistingService() => RustLib.instance.api.crateApiPanelApiDetectExistingService();

ServiceOverview getServiceOverview() => RustLib.instance.api.crateApiPanelApiGetServiceOverview();

ServiceOverview startService() => RustLib.instance.api.crateApiPanelApiStartService();

ServiceOverview stopService() => RustLib.instance.api.crateApiPanelApiStopService();

ServiceOverview restartService() => RustLib.instance.api.crateApiPanelApiRestartService();

ServiceOverview installService({required String targetDir }) => RustLib.instance.api.crateApiPanelApiInstallService(targetDir: targetDir);

ServiceOverview uninstallService() => RustLib.instance.api.crateApiPanelApiUninstallService();

ConfigSnapshot loadStructuredConfig() => RustLib.instance.api.crateApiPanelApiLoadStructuredConfig();

ConfigSnapshot saveStructuredConfig({required StructuredConfig payload , required bool restart }) => RustLib.instance.api.crateApiPanelApiSaveStructuredConfig(payload: payload, restart: restart);

ConfigSnapshot loadRawConfig() => RustLib.instance.api.crateApiPanelApiLoadRawConfig();

ConfigSnapshot saveRawConfig({required String raw , required bool restart }) => RustLib.instance.api.crateApiPanelApiSaveRawConfig(raw: raw, restart: restart);

LogSnapshot readLogTail({required int lines }) => RustLib.instance.api.crateApiPanelApiReadLogTail(lines: lines);

            class ConfigSnapshot  {
                final String path;
final String raw;
final StructuredConfig structured;
final String updatedAt;
final String? backupPath;

                const ConfigSnapshot({required this.path ,required this.raw ,required this.structured ,required this.updatedAt ,this.backupPath ,});

                static Future<ConfigSnapshot>  default_()=>RustLib.instance.api.crateApiPanelApiConfigSnapshotDefault();


                

                
        @override
        int get hashCode => path.hashCode^raw.hashCode^structured.hashCode^updatedAt.hashCode^backupPath.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ConfigSnapshot &&
                runtimeType == other.runtimeType
                && path == other.path&& raw == other.raw&& structured == other.structured&& updatedAt == other.updatedAt&& backupPath == other.backupPath;
        
            }

class CustomNetItem  {
                final String name;
final String cidr;

                const CustomNetItem({required this.name ,required this.cidr ,});

                static Future<CustomNetItem>  default_()=>RustLib.instance.api.crateApiPanelApiCustomNetItemDefault();


                

                
        @override
        int get hashCode => name.hashCode^cidr.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is CustomNetItem &&
                runtimeType == other.runtimeType
                && name == other.name&& cidr == other.cidr;
        
            }

class LogSnapshot  {
                final List<String> lines;
final int requested;
final String path;
final bool exists;

                const LogSnapshot({required this.lines ,required this.requested ,required this.path ,required this.exists ,});

                static Future<LogSnapshot>  default_()=>RustLib.instance.api.crateApiPanelApiLogSnapshotDefault();


                

                
        @override
        int get hashCode => lines.hashCode^requested.hashCode^path.hashCode^exists.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is LogSnapshot &&
                runtimeType == other.runtimeType
                && lines == other.lines&& requested == other.requested&& path == other.path&& exists == other.exists;
        
            }

class PanelAccountSummary  {
                final String username;
final String updatedAt;
final String credentialsPath;
final bool requiresPasswordChange;

                const PanelAccountSummary({required this.username ,required this.updatedAt ,required this.credentialsPath ,required this.requiresPasswordChange ,});

                static Future<PanelAccountSummary>  default_()=>RustLib.instance.api.crateApiPanelApiPanelAccountSummaryDefault();


                

                
        @override
        int get hashCode => username.hashCode^updatedAt.hashCode^credentialsPath.hashCode^requiresPasswordChange.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PanelAccountSummary &&
                runtimeType == other.runtimeType
                && username == other.username&& updatedAt == other.updatedAt&& credentialsPath == other.credentialsPath&& requiresPasswordChange == other.requiresPasswordChange;
        
            }

class PanelSession  {
                final bool authenticated;
final String? user;

                const PanelSession({required this.authenticated ,this.user ,});

                static Future<PanelSession>  default_()=>RustLib.instance.api.crateApiPanelApiPanelSessionDefault();


                

                
        @override
        int get hashCode => authenticated.hashCode^user.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PanelSession &&
                runtimeType == other.runtimeType
                && authenticated == other.authenticated&& user == other.user;
        
            }

class ServiceDetection  {
                final bool installed;
final bool runtimeReady;
final String runtimeIssue;
final String serviceName;
final String installDir;
final String configPath;
final String logPath;
final String executablePath;
final String commandLine;
final String bundledExecutablePath;
final String bundledConfigPath;

                const ServiceDetection({required this.installed ,required this.runtimeReady ,required this.runtimeIssue ,required this.serviceName ,required this.installDir ,required this.configPath ,required this.logPath ,required this.executablePath ,required this.commandLine ,required this.bundledExecutablePath ,required this.bundledConfigPath ,});

                static Future<ServiceDetection>  default_()=>RustLib.instance.api.crateApiPanelApiServiceDetectionDefault();


                

                
        @override
        int get hashCode => installed.hashCode^runtimeReady.hashCode^runtimeIssue.hashCode^serviceName.hashCode^installDir.hashCode^configPath.hashCode^logPath.hashCode^executablePath.hashCode^commandLine.hashCode^bundledExecutablePath.hashCode^bundledConfigPath.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ServiceDetection &&
                runtimeType == other.runtimeType
                && installed == other.installed&& runtimeReady == other.runtimeReady&& runtimeIssue == other.runtimeIssue&& serviceName == other.serviceName&& installDir == other.installDir&& configPath == other.configPath&& logPath == other.logPath&& executablePath == other.executablePath&& commandLine == other.commandLine&& bundledExecutablePath == other.bundledExecutablePath&& bundledConfigPath == other.bundledConfigPath;
        
            }

class ServiceOverview  {
                final ServiceDetection detection;
final ServiceStatus status;
final String summaryEndpoints;

                const ServiceOverview({required this.detection ,required this.status ,required this.summaryEndpoints ,});

                static Future<ServiceOverview>  default_()=>RustLib.instance.api.crateApiPanelApiServiceOverviewDefault();


                

                
        @override
        int get hashCode => detection.hashCode^status.hashCode^summaryEndpoints.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ServiceOverview &&
                runtimeType == other.runtimeType
                && detection == other.detection&& status == other.status&& summaryEndpoints == other.summaryEndpoints;
        
            }

class ServiceProcessInfo  {
                final String cpuDisplay;
final String memoryDisplay;
final String elapsed;
final String command;

                const ServiceProcessInfo({required this.cpuDisplay ,required this.memoryDisplay ,required this.elapsed ,required this.command ,});

                static Future<ServiceProcessInfo>  default_()=>RustLib.instance.api.crateApiPanelApiServiceProcessInfoDefault();


                

                
        @override
        int get hashCode => cpuDisplay.hashCode^memoryDisplay.hashCode^elapsed.hashCode^command.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ServiceProcessInfo &&
                runtimeType == other.runtimeType
                && cpuDisplay == other.cpuDisplay&& memoryDisplay == other.memoryDisplay&& elapsed == other.elapsed&& command == other.command;
        
            }

class ServiceStatus  {
                final String serviceName;
final String description;
final String loadState;
final String activeState;
final String subState;
final String unitFileState;
final BigInt pid;
final String mainCode;
final String mainStatus;
final String activeSince;
final String fragmentPath;
final bool isActive;
final bool installed;
final ServiceProcessInfo? process;

                const ServiceStatus({required this.serviceName ,required this.description ,required this.loadState ,required this.activeState ,required this.subState ,required this.unitFileState ,required this.pid ,required this.mainCode ,required this.mainStatus ,required this.activeSince ,required this.fragmentPath ,required this.isActive ,required this.installed ,this.process ,});

                static Future<ServiceStatus>  default_()=>RustLib.instance.api.crateApiPanelApiServiceStatusDefault();


                

                
        @override
        int get hashCode => serviceName.hashCode^description.hashCode^loadState.hashCode^activeState.hashCode^subState.hashCode^unitFileState.hashCode^pid.hashCode^mainCode.hashCode^mainStatus.hashCode^activeSince.hashCode^fragmentPath.hashCode^isActive.hashCode^installed.hashCode^process.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ServiceStatus &&
                runtimeType == other.runtimeType
                && serviceName == other.serviceName&& description == other.description&& loadState == other.loadState&& activeState == other.activeState&& subState == other.subState&& unitFileState == other.unitFileState&& pid == other.pid&& mainCode == other.mainCode&& mainStatus == other.mainStatus&& activeSince == other.activeSince&& fragmentPath == other.fragmentPath&& isActive == other.isActive&& installed == other.installed&& process == other.process;
        
            }

class StructuredConfig  {
                final String tcpBind;
final String quicBind;
final String wsBind;
final String network;
final List<String> whiteList;
final PlatformInt64 leaseDuration;
final String webBind;
final String username;
final String password;
final bool persistence;
final String cert;
final String key;
final String serverQuicBind;
final List<String> peerServers;
final String serverToken;
final List<CustomNetItem> customNets;

                const StructuredConfig({required this.tcpBind ,required this.quicBind ,required this.wsBind ,required this.network ,required this.whiteList ,required this.leaseDuration ,required this.webBind ,required this.username ,required this.password ,required this.persistence ,required this.cert ,required this.key ,required this.serverQuicBind ,required this.peerServers ,required this.serverToken ,required this.customNets ,});

                static Future<StructuredConfig>  default_()=>RustLib.instance.api.crateApiPanelApiStructuredConfigDefault();


                

                
        @override
        int get hashCode => tcpBind.hashCode^quicBind.hashCode^wsBind.hashCode^network.hashCode^whiteList.hashCode^leaseDuration.hashCode^webBind.hashCode^username.hashCode^password.hashCode^persistence.hashCode^cert.hashCode^key.hashCode^serverQuicBind.hashCode^peerServers.hashCode^serverToken.hashCode^customNets.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is StructuredConfig &&
                runtimeType == other.runtimeType
                && tcpBind == other.tcpBind&& quicBind == other.quicBind&& wsBind == other.wsBind&& network == other.network&& whiteList == other.whiteList&& leaseDuration == other.leaseDuration&& webBind == other.webBind&& username == other.username&& password == other.password&& persistence == other.persistence&& cert == other.cert&& key == other.key&& serverQuicBind == other.serverQuicBind&& peerServers == other.peerServers&& serverToken == other.serverToken&& customNets == other.customNets;
        
            }
            